language: python
dist: xenial
python:
  - "3.6"
# install dependencies
install:
- pip install Cython
- pip install -r requirements.txt
script:             # build sphinx document
- cd docs/
- make html
- cd -
deploy:              # deploy to github page
- provider: pages
  skip_cleanup: true
  local_dir: docs/_build/html
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  keep_history: true
# run tests

